import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Calendar from "../components/Calendar"

import { api } from "~/utils/api";

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <title>Another one</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <Calendar/>
       
      </main>
    </>
  );
};

export default Home;
