import './globals.css'
import Nav from './auth/Nav'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}) 
{
  return (
    <html lang="en">
        <body>
          {children}
          <Nav/>
          </body>
    </html>
  )
}
