import Head from 'next/head'
import {BsFillMoonStarsFill} from "react-icons/bs"
import {AiFillTwitterCircle,AiFillLinkedin,AiFillYoutube} from "react-icons/ai" 
import Image from "next/Image";
import deved from "../public/dev-ed-wave.png"
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";



export default function Home() {
  return (
    <>
      <Head>
        <title>Chad's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10 ' > 
        <section className=' min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
          <h1 className='text-xl font-burtons'>My Resume</h1>
          <ul className='flex items-center'>
            <li>
              <BsFillMoonStarsFill className='cursor-pointer text-2xl'/>
            </li>
            <li>
              <a className=' bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="#">Resume</a>

            </li>
          </ul>
          </nav>
          <div className='text-center p-10 '>
            <h2 className='text-5xl py-2 text-teal-600 font-medium'>Bhushan</h2>
            <h3 className='text-2xl py-2'>Developer and Designer.</h3>
            <p className='text-md py-5 leading-8 text-gray-800'> Hey I am bhushan lol . </p> 
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <AiFillLinkedin/>
            <AiFillTwitterCircle/>
            <AiFillYoutube/>
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden'>
            <Image src={deved} layout="fill" objectFit="cover" />
          </div>
        </section>
        {/*section two */ }

        <section>
          <div>
            <h3 className='text-3xl py-1'> Services I offer</h3>
            <p className='text-md py-2 leading-8 text-gray-800'>Lorem ipsum generaturm 
            <span className='text-teal-500'>started and collaborated with talented people to create digits for both business and consumer use </span>
             </p>

             <p className='text-md py-2 leading-8 text-gray-800'>
              I offer from a wide range of services. Including programming and teaching
             </p>
          </div>
          <div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              <Image src={design} width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
              <p className='py-2'>Creating elegan t diesigns suited for your needs according to design theory 
              </p>
              <h4 className='py-4 text-teal-600'>Design tools I use</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Figma</p>
              <p className='text-gray-800 py-1'>Webflow</p>
              <p>Canva</p>
            </div>

            <div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              <Image src={code} width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
              <p className='py-2'>Creating elegan t diesigns suited for your needs according to design theory 
              </p>
              <h4 className='py-4 text-teal-600'>Design tools I use</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Figma</p>
              <p className='text-gray-800 py-1'>Webflow</p>
              <p>Canva</p>
            </div>
          </div>


          <div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              <Image src={consulting} width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
              <p className='py-2'>Creating elegan t diesigns suited for your needs according to design theory 
              </p>
              <h4 className='py-4 text-teal-600'>Design tools I use</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Figma</p>
              <p className='text-gray-800 py-1'>Webflow</p>
              <p>Canva</p>
            </div>
          </div>



          </div>
        </section>


      </main>
    </>
  )
}
